/* -*- mode: c++; indent-tabs-mode: nil -*- */
/** @file grpc-module.h grpc module header file */
/*
    Qore grpc module

    Copyright (C) 2026 Qore Technologies, s.r.o.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#ifndef _QORE_GRPC_MODULE_H
#define _QORE_GRPC_MODULE_H

#include <qore/Qore.h>

// gRPC constant init function (generated by QPP from qc_grpc_types.qpp)
DLLLOCAL void init_grpc_types_constants(QoreNamespace& ns);

// gRPC hashdecl init functions (generated by QPP from qc_grpc_types.qpp)
DLLLOCAL TypedHashDecl* init_hashdecl_GrpcCallOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_GrpcCallResult(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_GrpcSslOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_GrpcChannelOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_GrpcServerOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_GrpcServiceInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_GrpcMethodInfo(QoreNamespace& ns);

// Global gRPC hashdecl pointers (initialized in grpc-module.cpp)
extern const TypedHashDecl* hashdeclGrpcCallOptions;
extern const TypedHashDecl* hashdeclGrpcCallResult;
extern const TypedHashDecl* hashdeclGrpcSslOptions;
extern const TypedHashDecl* hashdeclGrpcChannelOptions;
extern const TypedHashDecl* hashdeclGrpcServerOptions;
extern const TypedHashDecl* hashdeclGrpcServiceInfo;
extern const TypedHashDecl* hashdeclGrpcMethodInfo;

// Arrow hashdecl init functions (generated by QPP from QC_ArrowSchema.qpp)
DLLLOCAL TypedHashDecl* init_hashdecl_ArrowFieldInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_ArrowSchemaInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_ArrowIpcData(QoreNamespace& ns);

// Global Arrow hashdecl pointers
extern const TypedHashDecl* hashdeclArrowFieldInfo;
extern const TypedHashDecl* hashdeclArrowSchemaInfo;
extern const TypedHashDecl* hashdeclArrowIpcData;

// Arrow class and class ID pointers (defined by QPP-generated code)
extern QoreClass* QC_ARROWSCHEMA;
extern qore_classid_t CID_ARROWSCHEMA;
extern QoreClass* QC_ARROWRECORDBATCH;
extern qore_classid_t CID_ARROWRECORDBATCH;

// Arrow class init functions (generated by QPP)
DLLLOCAL QoreClass* initArrowSchemaClass(QoreNamespace& ns);
DLLLOCAL QoreClass* initArrowRecordBatchClass(QoreNamespace& ns);
DLLLOCAL QoreClass* initArrowIpcClass(QoreNamespace& ns);

// Namespace
extern QoreNamespace GrpcNs;

#endif // _QORE_GRPC_MODULE_H
